name = "whatsapp-rotation-api"
main = "stock-analysis-worker.js"
compatibility_date = "2024-01-01"

# KV 存储绑定
[[kv_namespaces]]
binding = "STOCK_WHATSAPP_ROTATION"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# 环境变量
[vars]
ENVIRONMENT = "production"

# Workers 路由
[env.production]
route = "https://your-domain.com/api/*"

# 开发环境
[env.development]
kv_namespaces = [
  { binding = "STOCK_WHATSAPP_ROTATION", id = "your-dev-kv-namespace-id" }
]